/* Generated By:JJTree: Do not edit this line. ASTHex1Conversion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package co.uk.ccmr.cbusio.sniffer.parser;

public
class ASTHex1Conversion extends SimpleNode {
  public ASTHex1Conversion(int id) {
    super(id);
  }

  public ASTHex1Conversion(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f5d20415a1ec36dc513395c3ee842db7 (do not edit this line) */
