/* Generated By:JJTree: Do not edit this line. ASTMacro.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package co.uk.ccmr.cbusio.sniffer.parser;

public
class ASTMacro extends SimpleNode {
  public String name;


public ASTMacro(int id) {
    super(id);
  }

  public ASTMacro(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  @Override
  public String toString() {
	  return name;
  }
}
/* JavaCC - OriginalChecksum=2560eaf66ee0aa5bcedcc59219cbe9aa (do not edit this line) */
