/* Generated By:JJTree: Do not edit this line. ASTReceive.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package co.uk.ccmr.cbusio.sniffer.parser;

import java.util.regex.Pattern;

public
class ASTReceive extends SimpleNode {
  public String trigger;
public Pattern pattern;


public ASTReceive(int id) {
    super(id);
  }

  public ASTReceive(ScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7345744eb62c4b05425da6d81210b871 (do not edit this line) */
