/* Generated By:JavaCC: Do not edit this line. ScriptParserTreeConstants.java Version 5.0 */
package co.uk.ccmr.cbusio.sniffer.parser;

public interface ScriptParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTACTION = 1;
  public int JJTINCLUDE = 2;
  public int JJTRECEIVE = 3;
  public int JJTMACRO = 4;
  public int JJTBLOCK = 5;
  public int JJTSTATEMENT = 6;
  public int JJTIFSTATEMENT = 7;
  public int JJTPAUSE = 8;
  public int JJTEXECUTE = 9;
  public int JJTTX = 10;
  public int JJTTXRX = 11;
  public int JJTPROMPT = 12;
  public int JJTTYPE = 13;
  public int JJTASSIGN = 14;
  public int JJTMESSAGE = 15;
  public int JJTTIMEOUT = 16;
  public int JJTNAME = 17;
  public int JJTEXPRESSION = 18;
  public int JJTCONDITIONALOREXPRESSION = 19;
  public int JJTCONDITIONALANDEXPRESSION = 20;
  public int JJTINCLUSIVEOREXPRESSION = 21;
  public int JJTEXCLUSIVEOREXPRESSION = 22;
  public int JJTANDEXPRESSION = 23;
  public int JJTEQUALITYEXPRESSION = 24;
  public int JJTRELATIONALEXPRESSION = 25;
  public int JJTSHIFTEXPRESSION = 26;
  public int JJTADDITIVEEXPRESSION = 27;
  public int JJTMULTIPLICATIVEEXPRESSION = 28;
  public int JJTUNARYEXPRESSION = 29;
  public int JJTPREINCREMENTEXPRESSION = 30;
  public int JJTPREDECREMENTEXPRESSION = 31;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 32;
  public int JJTPOSTFIXEXPRESSION = 33;
  public int JJTPRIMARYEXPRESSION = 34;
  public int JJTPRIMARYPREFIX = 35;
  public int JJTCHARCONVERSION = 36;
  public int JJTHEX1CONVERSION = 37;
  public int JJTHEX2CONVERSION = 38;
  public int JJTMID = 39;
  public int JJTPRIMARYSUFFIX = 40;
  public int JJTLITERAL = 41;


  public String[] jjtNodeName = {
    "Program",
    "Action",
    "Include",
    "Receive",
    "Macro",
    "Block",
    "Statement",
    "IfStatement",
    "Pause",
    "Execute",
    "Tx",
    "Txrx",
    "Prompt",
    "Type",
    "Assign",
    "Message",
    "Timeout",
    "Name",
    "Expression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "PostfixExpression",
    "PrimaryExpression",
    "PrimaryPrefix",
    "CharConversion",
    "Hex1Conversion",
    "Hex2Conversion",
    "Mid",
    "PrimarySuffix",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=7a7aaec694acba2b94963a81b9889346 (do not edit this line) */
